
export const dummyProducts = [
  {
    id: 1,
    name: "Chicken BBQ",
    price: 11.99,
    photo: "/img/1.jpg",
    size: 'Medium',
    quantity: 5,
    description: 'Chicken, red onions, corn, mozzarella, bbq sauce, tomato sauce',
  },
  {
    id: 2,
    name: "Shawarma Pizza",
    price: 12.99,
    photo: "/img/2.jpg",
    size: 'Large',
    quantity: 9,
    description: 'Mayonnaise & ketchup, spicy chicken, red onions, tomatoes, mozzarella',
  },
  {
    id: 3,
    name: "Chicken Suya",
    price: 9.99,
    photo: "/img/3.jpg",
    size: 'Medium',
    quantity: 3,
    description: 'Mayonnaise, spicy sauce, spicy chicken, bell peppers, red onions, suya sauce, tomato sauce, mozzarella, suya spice',
  },
  {
    id: 4,
    name: "Pepperoni",
    price: 8.99,
    photo: "/img/4.jpg",
    size: 'Small',
    quantity: 9,
    description: 'Pepperoni, mozzarella, tomato sauce',
  },
  {
    id: 5,
    name: "Beef Suya",
    price: 15.99,
    photo: "/img/5.jpg",
    size: 'Medium',
    quantity: 5,
    description: 'Mayonnaise, spicy sauce, spicy meatballs, bell peppers, red onions, mozzarella, suya sauce, tomato sauce, suya spice',
  },
  {
    id: 6,
    name: "Chicken Supreme",
    price: 7.99,
    photo: "/img/6.jpg",
    size: 'Large',
    quantity: 6,
    description: 'Spicy sauce, chicken and spicy chicken, mushrooms, bell peppers, olives, red onions, mozzarella, tomato sauce',
  },
  {
    id: 7,
    name: "Sweet Chili Chicken",
    price: 16.99,
    photo: "/img/7.jpg",
    size: 'Small',
    quantity: 8,
    description: 'Spicy sauce, chicken, chili pepper, mozzarella, sweet chili sauce, tomato sauce',
  },
  {
    id: 8,
    name: "Spicy Mixed Pizza",
    price: 11.00,
    photo: "/img/8.jpg",
    size: 'Large',
    quantity: 12,
    description: 'Spicy sauce, spicy meatballs, spicy chicken, chili pepper, corn, mozzarella, buffalo sauce, tomato sauce',
  },
  {
    id: 9,
    name: "Margherita",
    price: 19.00,
    photo: "/img/9.jpg",
    size: 'Medium',
    quantity: 13,
    description: 'Mozzarella, tomato sauce',
  },
  {
    id: 10,
    name: "Super Meaty",
    price: 11.09,
    photo: "/img/10.jpg",
    size: 'Small',
    quantity: 16,
    description: 'Chicken, pepperonni, sausages, mozzarella, tomato sauce',
  },
  {
    id: 11,
    name: "Cheesy Chicken",
    price: 12.90,
    photo: "/img/11.jpg",
    size: 'Large',
    quantity: 12,
    description: 'Chicken, tomatoes, cheddar, mozzarella, cheese sauce',
  },
  {
    id: 12,
    name: "Cheeseburger Pizza",
    price: 13.00,
    photo: "/img/12.jpg",
    size: 'Large',
    quantity: 8,
    description: 'Beef, tomatoes, red onions, cheddar, mozzarella, mayonnaise & ketchup, tomato sauce',
  },
];
